name = "palm_test"
version = "0.1.0"
license = "license"
author = "Syize"
maintainer = "syizeliu@gmail.com"
copyright = "Copyright 2026, Syize"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
external-modules = "netcdf"
link = ["netcdf"]
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
